on:
  push:

name: Jira

jobs:
  
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    
    steps:
    
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
   
    - name: Find issue in branch
      id: getIssue
      uses: atlassian/gajira-find-issue-key@v3
      with:
        string: DF-4
        
    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.getIssue.outputs.issue }}
        transition: "UAT"
